version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-ShopNewDb}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    image: shopnew:web-arm64
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      # PostgreSQL configuration
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_DB:-ShopNewDb};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD}
      # Stripe configuration
      - Stripe__PublishableKey=${STRIPE_PUBLISHABLE_KEY}
      - Stripe__SecretKey=${STRIPE_SECRET_KEY}
      - Stripe__WebhookSecret=${STRIPE_WEBHOOK_SECRET}
      # JWT configuration
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      # App base URL for redirects
      - App__BaseUrl=${APP_BASE_URL}
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge


