version: "3.9"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    image: shopnew:web-arm64
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Mongo__ConnectionString=${MONGO_CONNECTION_STRING}
      - Mongo__DatabaseName=${MONGO_DATABASE_NAME:-ShopNewDb}
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge


